import pandas
import json
import numpy


map_file = "Data Gathering\Mapdata\map DB limited bounds 4 of 5.csv"
grid = pandas.read_csv(map_file)
grid = grid.to_numpy()


output_file = "Maps\Test map limited bound DB 4 of 5 .json"

# Format for checkpoints is [x,y]
data = {
    "starting position": [39, 200],
    "starting direction": [1, 0],
    "checkpoints": [[
            [
                97,
                191
            ],
            [
                97,
                207
            ]
        ],
        [
            [
                105,
                205
            ],
            [
                118,
                205
            ]
        ],
        [
            [
                105,
                254
            ],
            [
                118,
                254
            ]
        ],
        [
            [
                117,
                257
            ],
            [
                117,
                279
            ]
        ],
        [
            [
                122,
                257
            ],
            [
                122,
                279
            ]
        ],
        [
            [
                142,
                257
            ],
            [
                142,
                279
            ]
        ],
        [
            [
                162,
                257
            ],
            [
                162,
                279
            ]
        ],
        [
            [
                188,
                262
            ],
            [
                188,
                282
            ]
        ],
        [
            [
                231,
                276
            ],
            [
                225,
                255
            ]
        ],
        [
            [
                257,
                244
            ],
            [
                273,
                259
            ]
        ],
        [
            [
                321,
                210 
            ],
            [
                325,
                240
            ]
        ],
        [
            [
                321,
                175
            ],
            [
                353,
                164
            ]
        ],
        [
            [
                275,
                131
            ],
            [
                277,
                164
            ]
        ],
        [
            [
                251,
                180
            ],
            [
                200,
                178
            ]
        ],
        [
            [
                192,
                183
            ],
            [
                194,
                209
            ]
        ],
        [
            [
                128,
                183
            ],
            [
                130,
                203
            ]
        ],
        [
            [
                282,
                226
            ],
            [
                290,
                259
            ]
        ]
        ,
        [
            [
                322,
                240
            ],
            [
                322,
                210
            ]
        ],
        [
            [
                323,
                209
            ],
            [
                387,
                205
            ]
        ],
        [
            [
                321,
                176
            ],
            [
                352,
                162
            ]
        ],
        [
            [
                277,
                131
            ],
            [
                277,
                164
            ]
        ],
        [
            [
                194,
                209
            ],
            [
                192,
                183
            ]
        ]
        ],
    "grid": grid.tolist()
}
print(data["checkpoints"].__len__())
with open(output_file, "w") as json_file:
    json.dump(data, json_file, indent=4)



